import { Repository } from 'typeorm';
import { Utilizador, Entidade, Permissao, Grupo } from '@/entities';
import * as bcrypt from 'bcrypt';

export class UtilizadorSeeder {
    static async run(
        utilizadorRepository: Repository<Utilizador>,
        entidadeRepository: Repository<Entidade>,
        permissaoRepository: Repository<Permissao>,
        grupoRepository: Repository<Grupo>,
    ) {
        const entidades = await entidadeRepository.find();
        const permissoes = await permissaoRepository.find();
        const grupos = await grupoRepository.find();

        const adminGroup = await grupoRepository.findOne({
            where: { nome: 'Administradores' },
        });

        const senhaHash = await bcrypt.hash('123456', 10);

        const utilizadores = [
            utilizadorRepository.create({
                nome: 'Administrador',
                username: 'admin',
                email: 'geral@antoniosergio.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: entidades,
                ativo: true,
                pbc: false,
                grupos: adminGroup ? [adminGroup] : [],
                permissoes,
            }),
            utilizadorRepository.create({
                nome: 'MicroLopes',
                username: 'microlopes',
                email: 'geral@microlopes.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: [entidades[0]],
                ativo: true,
                pbc: false,
                grupos: adminGroup ? [adminGroup] : [],
                permissoes,
            }),
            utilizadorRepository.create({
                nome: 'Nautis',
                username: 'nautis',
                email: 'geral@nautis.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: [entidades[0]],
                ativo: true,
                pbc: false,
                permissoes,
                grupos: adminGroup ? [adminGroup] : [],
            }),
            utilizadorRepository.create({
                nome: 'Guest',
                username: 'guest',
                email: '',
                telefone: '',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades,
                pbc: false,
                ativo: true,
                permissoes,
                grupos: [],
            }),
            utilizadorRepository.create({
                nome: 'David Lopes',
                username: 'davidLopes',
                email: 'geral@davidlopes.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: [entidades[1]],
                ativo: true,
                pbc: true,
                permissoes,
                grupos: adminGroup ? [adminGroup] : [],
            }),
            utilizadorRepository.create({
                nome: 'Ana Silva',
                username: 'anaSilva',
                email: 'ana.silva@exemplo.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: [entidades[1]],
                ativo: true,
                pbc: true,
                permissoes,
                grupos: grupos[2] ? [grupos[2]] : [],
            }),
            utilizadorRepository.create({
                nome: 'João Pereira',
                username: 'joaoPereira',
                email: 'joao.pereira@exemplo.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: [entidades[2]],
                ativo: true,
                pbc: true,
                permissoes,
                grupos: grupos[2] ? [grupos[2]] : [],
            }),
            utilizadorRepository.create({
                nome: 'Maria Fernandes',
                username: 'mariaFernandes',
                email: 'maria.fernandes@exemplo.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: [entidades[2]],
                ativo: true,
                pbc: true,
                permissoes,
                grupos: grupos[3] ? [grupos[3]] : [],
            }),
            utilizadorRepository.create({
                nome: 'Carlos Sousa',
                username: 'carlosSousa',
                email: 'carlos.sousa@exemplo.pt',
                senha: senhaHash,
                anexo: null,
                email_verificado_em: null,
                telefone_verificado_em: null,
                senha_alterada_em: null,
                token_recordar: null,
                entidades: [entidades[0], entidades[2]],
                ativo: true,
                pbc: true,
                permissoes,
                grupos: grupos[4] ? [grupos[4]] : [],
            })
        ];

        await utilizadorRepository.save(utilizadores);
        console.log('Seeders de Utilizador executados com sucesso!');
    }
}
